enableTelemetry: 0

nodeLinker: node-modules

packageExtensions:
  "@docsearch/react@*":
    dependencies:
      "@algolia/client-search": ">= 4.9.1 < 6"
  "@nrwl/devkit@*":
    dependencies:
      typescript: ^3 || ^4
  "@parcel/optimizer-image@*":
    dependencies:
      "@parcel/core": "*"
  "@parcel/types@*":
    dependencies:
      "@parcel/core": "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-3.3.1.cjs
