version: "3"

services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    command: sleep infinity
    environment:
      - HISTFILE=/command_history/.zsh_history
      - MEDPLUM_SERVER_URL=http://medplum:8103
      - MEDPLUM_CLIENT_ID=f54370de-eaf3-4d81-a17e-24860f667912
      - MEDPLUM_CLIENT_SECRET=75d8e7d06bf9283926c51d5f461295ccf0b69128e983b6ecdd5a9c07506895de
    volumes:
      - ${WORKSPACE_ROOT:-..}:/workspace:cached
      - devcontainer_node_modules:/workspace/node_modules
      - devcontainer_command_history:/command_history

  medplum:
    image: ghcr.io/bonfhir/medplum-devbox:v1.0.6
    depends_on:
      - postgres
      - redis
    ports:
      - "3000:3000"
      - "8103:8103"
    volumes:
      - ./medplum.config.json:/workspace/packages/server/medplum.config.json
  
  postgres:
    image: postgres:12-bullseye
    command: postgres -c config_file=/usr/local/etc/postgres/postgres.conf
    environment:
      - POSTGRES_USER=medplum
      - POSTGRES_PASSWORD=medplum
    ports:
      - '5432:5432'
    volumes: 
      - postgres_data:/var/lib/postgresql/data
      - ./postgres.conf:/usr/local/etc/postgres/postgres.conf
      - ./load_extensions.sql:/docker-entrypoint-initdb.d/load_extensions.sql

  redis:
    image: redis:6-bullseye
    command: redis-server --requirepass medplum
    ports:
      - '6379:6379'

volumes:
  devcontainer_node_modules:
  devcontainer_command_history:
  postgres_data:
