name: Bonfhir Main

on:
  push:
    branches: [main]
  
jobs:
  build_main:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Required to support lerna --since command

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: yarn

      - name: Install packages
        run: yarn install --immutable

      - name: Check
        run: yarn lerna run check

      - name: Build
        run: yarn lerna run build

      - name: Test
        run: yarn lerna run test -- --coverage --passWithNoTests

      - name: Upload code coverage
        uses: codecov/codecov-action@v3

      - name: Authenticate SSH deploy key
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.GH_PAGES_DEPLOY }}
      
      - name: Deploy doc
        env:
          USE_SSH: true
          DEPLOYMENT_BRANCH: main
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "gh-actions"
          yarn lerna run deploy --scope=@bonfhir/docs --since=HEAD^1
